### ISSUE TITLE
Index.html report generation

### ISSUE THREAD

**Issue by subbu3397** [AOEpeople/geb-spock-reports#13] opened 2018-11-01 07:45 UTC
May I know when will be the index.html file generated?

**Comment by tilmanginzel** [comment] 2018-11-02 17:42
HI @subbu3397, the index.html will be created when you run `./gradlew test`. I would recommend to always run `./gradlew clean test` to make sure that no old test results are part of the report.

**Comment by jacattau** [comment] 2019-01-17 16:47
Hi @tilmanginzel, I am not getting an index.html either after implementing this into my project.  I have everything from your project into mine, but the only difference I can see is in `com.athaydes.spockframework.report.IReportCreator.properties` mine appears to be unused, where it is showing grey but yours is showing blue.  Could this be the issue and how would I resolve that?

**Comment by jacattau** [comment] 2019-01-17 17:06
I found the issue and I suspect @subbu3397 did the same thing.  When creating the META-INF folder it is META-INF/services and NOT META-INF.services.  

That was confusing to distinguish based on how your project looked in IntelliJ.

**Comment by tilmanginzel** [comment] 2019-01-17 19:43
@jacattau Great to see that you have found the root cause. :)

**Comment by tilmanginzel** [comment] 2019-01-24 18:57
@subbu3397 I am going to close this issue as no further context was provided. Feel free to reopen if you have further questions!

**Closed by tilmanginzel** 2019-01-24 18:57 UTC
Labels: question
